/**:
  ros__parameters:
    feedback_period_ms: 1
    joints:
      joint0:
        board_type: "can_motor"
        board_id: 1
        id: 0
        control_type: "speed"
        command_period_ms: 10
      joint1:
        board_type: "can_motor"
        board_id: 1
        id: 1
        control_type: "speed"
        command_period_ms: 10
      